const recipes = [

   {
            "id": 1,
            "img": "Dishes Images/Chicken tikkaa  masala.jpg",
            "typeofDish": "Non-Veg",
            "name": "Chicken Tikka Masala",
            "preparationTime": "15 minutes",
            "cockingTime": "40 minutes",
            "totalTime": "55 minutes + marination time (minimum 1 hour)",
            "Serving": "4 servings",
            "ingredients": ["500g chicken breast or thighs (boneless, cut into cubes), 1/2 cup plain yogurt, 1 tablespoon ginger-garlic paste, 1 tablespoon lemon juice, 1 teaspoon ground cumin, 1teaspoon ground coriander, 1 teaspoon paprika (for colour) 1/2 teaspoon turmeric powder, 1 teaspoon garam masala,  Salt to taste, 2 tablespoons vegetable oil,  2 tablespoons butter or oil,  1 large onion, finely chopped,  2 medium tomatoes, pureed , 1 tablespoon ginger-garlic paste ,   1 teaspoon ground cumin,  1 teaspoon ground coriander , 1 teaspoon red chili powder (adjust to taste) , 1 teaspoon garam masala,  1/2 teaspoon turmeric powder,  1/2 cup heavy cream ,  Fresh coriander leaves (for garnish),  Salt to taste ",],
            "instructions": [
                "In a large bowl, mix the yogurt, ginger-garlic paste, lemon juice, cumin, coriander, paprika, turmeric, garam masala, salt, and vegetable oil. Add the chicken pieces, coat them well, and marinate for at least 1 hour (preferably overnight for better flavour). ",
                "Preheat the oven to 200°C (390°F).  Place the marinated chicken on a baking tray and bake for 15-20 minutes or grill until fully cooked. Alternatively, you can cook the chicken in a hot pan with a little oil until golden on the outside and cooked through. ",
                " In a large pan, melt butter or heat oil over medium heat. Add the chopped onions and sauté until golden brown. Add ginger-garlic paste and cook until the raw smell disappears. Add the tomato puree and cook for 5-7 minutes until the oil separates from the mixture.",
                "Add cumin, coriander, turmeric, chili powder, and garam masala. Stir and cook for another minute.",
                "Add water as needed to adjust the consistency of the gravy. Pour in the cream and mix well. Simmer for 5 minutes on low heat.",
                " Add the cooked chicken pieces to the gravy. Let it simmer for another 5-10 minutes to absorb all the Flavors. Garnish with fresh coriander leaves. Serve hot with naan, roti, or steamed basmati rice."
            ],
            "nurtrition": {
                "Calories":" 400 kcal",
                "Protein":"32g",
                "Fat":"20g",
                "Fiber":"4g",
                "Carbohydrates":"18g",
            },
        },
   

    {
            "id": 2,
            "img": "Dishes Images/butter chicken.jpg",
            "name": "Butter Chicken ",
            "typeofDish": "Non-Veg",
            "preparationTime": " 15 minutes",
            "cockingTime": " 40 minutes",
            "Serving": "4 servings",
            "totalTime": "55 minutes + marination time (minimum 1 hour)",
            "inngredients": "500g chicken breast or thighs (boneless, cut into cubes), 1/2 cup plain yogurt,  1 tablespoon ginger-garlic paste,  1 tablespoon lemon juice,  1 teaspoon ground cumin,  1 teaspoon ground coriander,  1 teaspoon garam masala,  1/2 teaspoon turmeric powder,  1 teaspoon chili powder (adjust to taste), Salt to taste, 2 tablespoons vegetable oil, 2 tablespoons butter,  1 large onion, finely chopped, 2 medium tomatoes, pureed,  1 tablespoon ginger-garlic paste,  1/2 cup heavy cream,  1 teaspoon ground cumin, 1 teaspoon garam masala, 1 teaspoon ground coriander, 1/2 teaspoon turmeric powder, 2 tablespoons cashew paste (optional),  Salt to taste, Fresh coriander for garnish",
            "instructions": [
                "In a bowl, mix yogurt, ginger-garlic paste, lemon juice, cumin, coriander, garam masala, turmeric, chili powder, salt, and oil. Add the chicken cubes, coat well, and marinate for at least 1 hour (preferably overnight for better flavour).",
                " Preheat the oven to 200°C (390°F). Place the marinated chicken on a baking tray and bake for 15-20 minutes or grill until fully cooked. Alternatively, you can cook the chicken in a hot pan with a little oil until golden on the outside and cooked through.",
                "In a large pan, melt butter over medium heat. Add chopped onions and sauté until golden brown. Add ginger-garlic paste and cook until the raw smell disappears. Add the tomato puree and cook until oil starts to separate (about 5-7 minutes). ",
                "Add cumin, coriander, chili powder, turmeric, and garam masala. Stir well. Add cashew paste if using, and cook for another 2 minutes. Pour in the cream and mix well. Simmer for 5 minutes on low heat. ",
                "Add the cooked chicken to the gravy. Let it simmer for 5-10 minutes, allowing the chicken to absorb the flavours.",
                "Garnish with fresh coriander. Serve hot with naan, roti, or steamed basmati rice. ",
            ],
            "nurtrition": {
                "Calories":"450 kcal",
                "Protein":" 30g",
                "Fat":"28g",
                "Fiber":"3g",
                "Carbohydrates":"15g",
            },
        },
    
   
        {
            "id": 3,
            "img": "Dishes Images/palak chicken.jpg",
            "name": "Palak Chicken",
            "typeofDish": "Non-Veg",
            "preparationTime": "10 minutes ",
            "cockingTime": "40 minutes ",
            "totalTime": "50 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g chicken (bone-in or boneless, cut into pieces), 1 tablespoon ginger-garlic paste, 1 teaspoon turmeric powder, 1 teaspoon red chili powder,1 teaspoon ground coriander,1 teaspoon garam masala, Salt to taste, 200g fresh spinach leaves, 1 large onion, finely chopped, 2 tomatoes, finely chopped or pureed,1 tablespoon ginger-garlic paste, 1 teaspoon cumin seeds, 2 green chilies (optional, for extra heat),1 teaspoon ground coriander,1/2 teaspoon garam masala, 1 teaspoon kasseri Methi (dried fenugreek leaves),2 tablespoons cream or yogurt (optional), Salt to taste, 2 tablespoons oil or ghee. ",
            "instructions": [
                "Wash the spinach thoroughly. Boil water in a large pot and blanch the spinach for 2-3 minutes. Immediately transfer the spinach to ice-cold water to retain the green color.  Drain and blend the spinach into a smooth puree. Set aside.",
                " In a bowl, mix the chicken with ginger-garlic paste, turmeric powder, red chili powder, ground coriander, garam masala, and salt. Heat oil or ghee in a large pan, and fry the marinated chicken until browned. Remove and set aside. ",
                "In the same pan, add cumin seeds and let them sizzle. Add the chopped onions and sauté until golden brown. Add ginger-garlic paste and cook until the raw smell disappears. ",
                "Add chopped tomatoes (or tomato puree) and cook until the oil starts separating.  Add green chilies (if using), ground coriander, and salt. Cook for another 2-3 minutes. ",
                " Add the cooked chicken pieces back into the pan and stir. Add the spinach puree and Kasseri Methi. Cover and simmer for 10 minutes, allowing the Flavors to blend. ",
                " Add cream or yogurt for a richer texture (optional). Sprinkle garam masala and mix well.  Serve hot with roti, naan, or steamed rice.",
            ],
            "nurtrition": {
               "Calories":"350 kcal",
                "Protein":" 32g",
                "Fat":"18g",
                "Fiber":"4g",
                "Carbohydrates":"10g",
            },
        },

        {
            "id": 4,
            "img": "Dishes Images/Chicken biryani.jpg",
            "name": "Chicken Biryani",
            "typeofDish": "Non-Veg",
            "preparationTime": "20 minutes",
            "cockingTime": "1 hour ",
            "totalTime": "1 hour 20 minutes",
            "Serving": "4 servings",
            "inngredients": "500g chicken (bone-in or boneless, cut into pieces), 1/2 cup yogurt, 1 tablespoon ginger-garlic paste, 1 teaspoon red chili powder,1/2 teaspoon turmeric powder, 1 teaspoon ground coriander, 1 teaspoon garam masala, 1 tablespoon lemon juice, Salt to taste, 2 cups basmati rice (washed and soaked for 30 minutes), 4 cups water, 2-3 cloves, 2-3 green cardamom pods, 1 bay leaf, 1 cinnamon stick, 2 large onions, thinly sliced, 2 tomatoes, chopped, 2 green chilies (optional), 1 tablespoon ginger-garlic paste, 1 teaspoon cumin seeds, 1/2 cup chopped mint leaves, 1/2 cup chopped coriander leaves, 1/2 teaspoon saffron strands (soaked in 2 tablespoons warm milk), 3 tablespoons ghee or oil,1/4 cup fried onions (for garnish). ",
            "instructions": [
                "In a bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric powder, ground coriander, garam masala, lemon juice, and salt. Add the chicken pieces and coat them well.  Marinate for at least 1 hour (preferably overnight). ",
                "In a large pot, bring water to a boil. Add cloves, cardamom, bay leaf, cinnamon stick, and salt. Add the soaked rice and cook until 70% done (the rice should still have a bite). Drain and set aside. ",
                " Heat ghee or oil in a large pan and add cumin seeds. Add the sliced onions and sauté until golden brown. Add ginger-garlic paste and green chilies, cooking until the raw smell disappears. Add chopped tomatoes and cook until the oil starts separating.  Add the marinated chicken and cook for 15-20 minutes until the chicken is fully cooked and tender. ",
                "In a large heavy-bottomed pot, start layering the chicken and rice. Spread half of the chicken mixture at the bottom, followed by a layer of rice. Sprinkle mint leaves, coriander leaves, saffron milk, and fried onions. Repeat with the remaining chicken and rice. Finish with a final layer of rice, saffron milk, mint, coriander, and fried onions. ",
                "Cover the pot tightly with a lid or seal with dough to prevent steam from escaping. Cook on low heat for 20-25 minutes. You can place the pot on a tawa (griddle) to prevent direct heat from burning the bottom layer",
                "Gently fluff the rice and chicken to mix the layers. Serve hot with raita or a salad",
            ],
            "nurtrition": {
                "Calories":" 600 kcal ",
                "Protein":" 28g",
                "Fat":"22g",
                "Fiber":"4g",
                "Carbohydrates":"70g",
            },
        },

        {
            "id": 5,
            "img": "Dishes Images/Mutton biryani.jpg",
            "name": "Mutton Biryani",
            "typeofDish": "Non-Veg",
            "preparationTime": "30 minutes ",
            "cockingTime": "1 hour 30 minutes ",
            "totalTime": "2 hours ",
            "Serving": "4 servings",
            "inngredients": "500g mutton (goat or lamb, cut into pieces), 1/2 cup plain yogurt, 1 tablespoon ginger-garlic paste, 1 teaspoon red chili powder, 1/2 teaspoon turmeric powder, 1 teaspoon ground coriander, 1 teaspoon garam masala, 1 tablespoon lemon juice, Salt to taste, 2 cups basmati rice (washed and soaked for 30 minutes), 4 cups water, 2-3 cloves, 2-3 green cardamom pods,1 bay leaf, 1 cinnamon stick, 2 large onions, thinly sliced, 2 tomatoes, chopped, 2 green chilies (optional), 1 tablespoon ginger-garlic paste, 1 teaspoon cumin seeds, 1/2 cup chopped mint leaves, 1/2 cup chopped coriander leaves, 1/2 teaspoon saffron strands (soaked in 2 tablespoons warm milk), 3 tablespoons ghee or oil,1/4 cup fried onions (for garnish) ",
            "instructions": [
                "In a large bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric, ground coriander, garam masala, lemon juice, and salt.  Add the mutton pieces, coat well, and marinate for at least 1-2 hours (preferably overnight). ",
                "Heat ghee or oil in a pressure cooker or heavy-bottomed pan. Add cumin seeds and let them crackle. Add sliced onions and sauté until golden brown. Add ginger-garlic paste and green chilies, cooking until the raw smell disappears. Add chopped tomatoes and cook until the oil starts separating from the mixture. Add the marinated mutton and cook on medium heat for 15-20 minutes, stirring occasionally. Add water and pressure cook for 20-25 minutes until the mutton is tender. If using a regular pan, cook for 45-60 minutes until the meat is soft. ",
                " In a large pot, bring water to a boil. Add cloves, cardamom, bay leaf, cinnamon stick, and salt. Add the soaked rice and cook until 70% done (the rice should still have a bite). Drain and set aside.",
                "In a large heavy-bottomed pot, start layering the cooked mutton and rice. Spread half of the mutton at the bottom, followed by a layer of rice.Sprinkle mint leaves, coriander leaves, saffron milk, and fried onions. Repeat with the remaining mutton and rice. Finish with a final layer of rice, saffron milk, mint, coriander, and fried onions.",
                "Cover the pot tightly with a lid or seal with dough to trap steam. Place the pot on low heat for 20-30 minutes to allow the Flavors to blend. You can also place the pot on a tawa (griddle) to prevent direct heat from burning the bottom layer. ",
                " Fluff the rice and mutton gently before serving. Serve hot with raita or a side salad.",
            ],
            "nurtrition": {
                "Calories":"650 kcal",
                "Protein":" 35g",
                "Fat":"28g",
                "Fiber":"5g",
                "Carbohydrates":"70g",
            }
        },

        {
            "id": 6,
            "img": "Dishes Images/Fish Curry.jpg",
            "name": "Fish Curry",
            "typeofDish": "Non-Veg",
            "preparationTime": "15 minutes",
            "cockingTime": "30 minutes ",
            "totalTime": "45 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g fish fillets (such as kingfish, tilapia, or cod), 1 teaspoon turmeric powder, 1 teaspoon red chili powder, 1 tablespoon lemon juice, 2 tablespoons oil (coconut oil or vegetable oil),1 large onion, finely chopped, 2 tomatoes, finely chopped or pureed, 1 tablespoon ginger-garlic paste,1 teaspoon cumin seed, 1 teaspoon mustard seeds, 2-3 green chilies (slit), 1 teaspoon turmeric powder, 1 teaspoon coriander powder, 1 teaspoon red chili powder, 1 teaspoon garam masala, 1/2 cup coconut milk (optional), 2 tablespoons tamarind pastes or juice, Fresh coriander leaves for garnish, Salt to taste.",
            "instructions": [
                " In a bowl, mix the turmeric powder, red chili powder, lemon juice, and salt. Coat the fish fillets with this mixture and let them marinate for 15 minutes.",
                " Heat 1 tablespoon oil in a pan and lightly fry the marinated fish for 2-3 minutes on each side until golden brown. Remove from the pan and set aside. ",
                "In the same pan, heat the remaining oil. Add mustard seeds and cumin seeds, and let them splutter. Add chopped onions and sauté until golden brown. Add ginger-garlic paste and cook until the raw smell disappears.Add chopped tomatoes (or tomato puree) and cook until the oil separates from the mixture. Add turmeric powder, coriander powder, red chili powder, and garam masala. Cook for another 2 minutes.",
                " Add the tamarind paste and a cup of water. Bring the curry to a boil and then lower the heat to let it simmer for 10 minutes. If using coconut milk, add it at this stage and mix well.",
                " Gently slide the fried fish fillets into the curry. Simmer for 5-7 minutes on low heat, allowing the fish to absorb the Flavors of the curry. ",
                "Garnish with fresh coriander leaves. Serve hot with steamed rice or roti. ",
            ],
            "nurtrition": {
                "Calories":"320 kcal",
                "Protein":" 30g",
                "Fat":"15g",
                "Fiber":"3g",
                "Carbohydrates":"10g",
            },
        },


        {
            "id": 7,
            "img": "Dishes Images/Prawn Malai Curry.jpg",
            "name": " Prawn Malai Curry",
            "typeofDish": "Non-Veg",
            "preparationTime": "15 minutes ",
            "cockingTime": "30 minutes ",
            "totalTime": " 45 minutes",
            "Serving": "4 servings",
            "inngredients": "500g prawns (peeled and deveined), 1/2 teaspoon turmeric powder, 1/2 teaspoon red chili powder, 2 tablespoons mustard oil (or vegetable oil),1 large onion, finely chopped, 1 tablespoon ginger-garlic paste, 2 green chilies, slit,1 teaspoon cumin seed, 1/2 teaspoon turmeric powder, 1/2 teaspoon red chili powder, 1 cup coconut milk, 1 tablespoon fresh cream (optional), 2 tablespoons grated coconut (optional), 1 teaspoon garam masala, 2 tablespoons ghee, Fresh coriander leaves for garnish, Salt to taste. 1 tablespoon lemon juice, Salt to taste, ",
            "instructions": [
                " In a bowl, mix the prawns with turmeric, red chili powder, lemon juice, and salt. Let them marinate for 10-15 minutes.",
                "Heat 1 tablespoon mustard oil in a pan. Lightly fry the marinated prawns for 2-3 minutes until they turn pink. Remove from the pan and set aside. ",
                " In the same pan, heat the remaining mustard oil. Add cumin seeds and let them crackle. Add chopped onions and sauté until golden brown. Add ginger-garlic paste and cook until the raw smell disappears.  Add slit green chilies, turmeric powder, and red chili powder, and cook for 2 minutes. ",
                "Add coconut milk and grated coconut (if using) to the onion mixture. Simmer the curry on low heat for 10 minutes, allowing the Flavors to blend. Add salt to taste. ",
                "Gently add the fried prawns to the curry. Cook for another 5-7 minutes, allowing the prawns to soak in the curry. Add fresh cream and garam masala, stirring well. ",
                "Add ghee for extra richness before serving. Garnish with fresh coriander leaves. Serve hot with steamed rice or roti. ",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 28g",
                "Fat":"20g",
                "Fiber":"2g",
                "Carbohydrates":"8g",
            },
        },


        {
            "id": 8,
            "img": "Dishes Images/Tandoori chicken.jpg",
            "name": "Chicken Tandoori ",
            "typeofDish": "Non-Veg",
            "preparationTime": "15 minutes ",
            "cockingTime": "30 minutes +  6 hours (or overnight)",
            "totalTime": " 6 hours 45 minutes",
            "Serving": "4 servings",
            "inngredients": "1 whole chicken (cut into 4 pieces or use 4 chicken legs), 1/2 cup thick yogurt 1 tablespoon ginger-garlic paste, 1 tablespoon lemon juice,1 teaspoon red chili powder, 1/2 teaspoon turmeric powder, 1 teaspoon ground cumin, 1 teaspoon ground coriander, 1 teaspoon garam masala,1/2 teaspoon black pepper powder, 1 tablespoon vegetable oil, Fresh lemon wedges Chopped coriander leaves Sliced onions Salt to taste. ",
            "instructions": [
                "Make deep slits on the chicken pieces to help the marinade penetrate. In a bowl, mix yogurt, ginger-garlic paste, lemon juice, red chili powder, turmeric, ground cumin, ground coriander, garam masala, black pepper, vegetable oil, salt, and red food color (if using). ",
                " Rub the marinade all over the chicken pieces, making sure it gets into the slits. Cover and refrigerate for at least 6 hours, or preferably overnight for the best flavour. ",
                "Preheat your oven to 200°C (400°F). If you have a charcoal grill, prepare it by lighting the coals until they're hot. ",
                " If using an oven, place the marinated chicken on a baking tray lined with foil. Bake for 25-30 minutes, turning the chicken halfway through, until it is cooked through and slightly charred on the edges. ",
                "If using a grill, place the chicken over the hot coals and cook for 20-25 minutes, turning occasionally until the chicken is cooked and has a nice char. ",
                "Garnish the chicken tandoori with fresh lemon wedges, sliced onions, and chopped coriander leaves. Serve hot with naan, roti, or rice, and a side of mint chutney.",
            ],
            "nurtrition": {
                "Calories":"360 kcal",
                "Protein":" 35g",
                "Fat":"18g",
                "Fiber":"2g",
                "Carbohydrates":"5g",
            },
        },

        {
            "id": 9,
            "img": "Dishes Images/Seekh kabab.jpg",
            "name": " Seekh Kebab ",
            "typeofDish": "Non-Veg",
            "preparationTime": " 20 minutes",
            "cockingTime": "1 hour (Marination Time ) + 20 minutes",
            "totalTime": " 1 hour 40 minutes",
            "Serving": "4 servings",
            "inngredients": "500g minced lamb or chicken, 1 medium onion, finely chopped, 1 tablespoon ginger-garlic paste, 2 green chilies, finely chopped, 1 tablespoon coriander powder, 1 teaspoon cumin powder, 1 teaspoon garam masala, 1 teaspoon red chili powder, 1/2 teaspoon turmeric powder, 1 tablespoon lemon juice,1/4 cup fresh coriander leaves, finely chopped,1/4 cup fresh mint leaves, finely chopped, 1 tablespoon vegetable oil or melted butter (for basting), Salt to taste. ",
            "instructions": [
                " In a large mixing bowl, combine minced meat (lamb or chicken), chopped onions, ginger-garlic paste, green chilies, coriander powder, cumin powder, garam masala, red chili powder, turmeric powder, lemon juice, fresh coriander, fresh mint, and salt.",
                "Mix everything thoroughly until well combined.- Cover the mixture and refrigerate for at least 1 hour to allow the Flavors to develop. ",
                "Once the mixture is marinated, take small portions of the meat mixture and mold it around metal or wooden skewers, shaping it into long kebabs. If using wooden skewers, soak them in water for 30 minutes to prevent burning. ",
                " Preheat a grill or oven to 200°C (400°F). If grilling, place the kebabs on the hot grill and cook for 15-20 minutes, turning occasionally, until they are cooked through and lightly charred. ",
                "If using an oven, place the skewers on a baking tray lined with foil and bake for 20 minutes, turning once halfway through. Baste the kebabs with oil or melted butter during cooking to keep them moist. ",
                " Serve the seekh kebabs hot with mint chutney, lemon wedges, and sliced onions. They can also be served with naan or as a filling for wraps. ",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 25g",
                "Fat":"18g",
                "Fiber":"2g",
                "Carbohydrates":"6g",
            },
        },

        {
            "id": 10,
            "img": "Dishes Images/mutton Rogan josh.jpg",
            "name": "Mutton Rogan Josh",
            "typeofDish": "Non-Veg",
            "preparationTime": "20 minutes ",
            "cockingTime": "1 hour 30 minutes ",
            "totalTime": "1 hour 50 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g mutton (goat or lamb, cut into medium pieces), 2 tablespoons mustard oil (or vegetable oil), 1 large onion, finely sliced, 1 tablespoon ginger-garlic paste, 1/2 cup plain yogurt (whisked), 2-3 green cardamom pods, 2-3 cloves, 1 bay leaf, 1 cinnamon stick, 1/2 teaspoon cumin seeds,1 teaspoon red chili powder (preferably Kashmiri red chili powder for color), 1 teaspoon ground coriander, 1/2 teaspoon turmeric powder,1/2 teaspoon fennel powder, 1/2 teaspoon garam masala, 2-3 tablespoons water, Fresh coriander leaves for garnish Salt to taste. ",
            "instructions": [
                " Heat mustard oil in a large heavy-bottomed pan or pressure cooker over medium heat. Add the cumin seeds, cardamom pods, cloves, bay leaf, and cinnamon stick. Let them sizzle for a minute until fragrant. Add the sliced onions and sauté until golden brown. ",
                "Add the ginger-garlic paste to the onions and cook for another 2-3 minutes until the raw smell disappears. Stir in the red chili powder, ground coriander, turmeric powder, and fennel powder. Add the mutton pieces and sear them on all sides until they turn brown, about 8-10 minutes. ",
                "Lower the heat and add the whisked yogurt, a little at a time, stirring continuously to prevent curdling. Cook the mutton in the yogurt and spices for about 10-15 minutes, allowing the yogurt to thicken.",
                "Add 2-3 tablespoons of water, cover the pan, and let the mutton cook on low heat for 1-1.5 hours until the meat is tender and the oil starts separating from the gravy.",
                "If using a pressure cooker, cook for 5-6 whistles until the mutton is tender. Stir occasionally and add more water if needed to adjust the gravy's consistency. ",
                "Stir in the garam masala and cook for another 5 minutes. Garnish with fresh coriander leaves. Serve hot with steamed rice, naan, or roti. ",
            ],
            "nurtrition": {
                "Calories":"450 kcal",
                "Protein":" 30g",
                "Fat":"25g",
                "Fiber":"2g",
                "Carbohydrates":"10g",
            },
        },

        {
            "id": 11,
            "img": "Dishes Images/chicken 65.jpg",
            "name": " Chicken 65",
            "typeofDish": "Non-Veg",
            "preparationTime": "15 minutes ",
            "cockingTime": "1 hour + 20 minutes ",
            "totalTime": " 1 hour 35 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g chicken (boneless, cut into bite-sized pieces),1/2 cup yogurt, 1 tablespoon ginger-garlic paste, 1 teaspoon red chili powder, 1/2 teaspoon turmeric powder, 1 teaspoon garam masala,1 tablespoon lemon juice, 1/2 cup all-purpose flour, 1/4 cup cornstarch, 1/2 teaspoon red chili powder, 1/2 teaspoon black pepper powder, Oil for deep frying, Fresh curry leaves, Lemon wedges, Sliced onions, Salt to taste. ",
            "instructions": [
                " In a large bowl, combine yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, lemon juice, and salt. Add the chicken pieces and mix well to coat them evenly. Cover and refrigerate for at least 1 hour. ",
                " In a separate bowl, mix all-purpose flour, cornstarch, red chili powder, black pepper powder, and salt. ",
                " Remove the marinated chicken from the refrigerator. Dredge each piece of chicken in the flour mixture, ensuring an even coating. ",
                "Heat oil in a deep-frying pan or wok over medium heat. Fry the coated chicken pieces in batches, making sure not to overcrowd the pan.  ",
                "Fry until golden brown and crispy, about 4-5 minutes per batch.Remove the fried chicken with a slotted spoon and drain on paper towels. ",
                " In a small pan, heat a little oil and fry fresh curry leaves until crisp. Garnish the fried chicken with the crispy curry leaves, lemon wedges, and sliced onions. Serve hot as a snack or appetizer. ",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 25g",
                "Fat":"20g",
                "Fiber":"2g",
                "Carbohydrates":"20g",
            },
        },

        {
            "id": 12,
            "img": "Dishes Images/Hyderabadi biriyani.jpg",
            "name": " Hyderabadi Chicken",
            "typeofDish": "Non-Veg",
            "preparationTime": "20 minutes ",
            "cockingTime": "45 minutes",
            "totalTime": "1 hour 5 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g chicken (cut into pieces),1/2 cup plain yogurt, 1 tablespoon ginger-garlic paste, 1 tablespoon lemon juice, 1 teaspoon red chili powder, 1/2 teaspoon turmeric powder, 1 teaspoon ground coriander, 1 teaspoon garam masala, 2 tablespoons oil (vegetable or ghee), 2 large onions, finely sliced, 2 tomatoes, chopped or pureed, 1 tablespoon ginger-garlic paste, 2-3 green chilies, slit (optional), 1 teaspoon cumin seeds,1/2 teaspoon turmeric powder, 1 teaspoon red chili powder, 1 teaspoon ground coriander, 1 teaspoon garam masala, 1/2 cup coconut milk (optional), Fresh coriander leaves for garnish, Salt to taste. ",
            "instructions": [
                "In a large bowl, combine yogurt, ginger-garlic paste, lemon juice, red chili powder, turmeric powder, ground coriander, garam masala, and salt. Add chicken pieces and mix well. Cover and refrigerate for at least 1 hour, or overnight for best results. ",
                "Heat oil or ghee in a large pan over medium heat. Add cumin seeds and let them sizzle. Add sliced onions and sauté until golden brown. Add ginger-garlic paste and cook for 2-3 minutes until the raw smell disappears. Add chopped or pureed tomatoes and cook until the oil starts separating from the mixture.",
                "Add turmeric powder, red chili powder, ground coriander, and garam masala to the onion-tomato mixture. ",
                " Add the marinated chicken and cook on medium heat for 10-15 minutes, stirring occasionally. If using coconut milk, add it now and mix well. ",
                "Cover and cook on low heat for 20-25 minutes, or until the chicken is cooked through and the sauce has thickened. Stir occasionally and add water if needed to adjust the consistency. ",
                "Garnish with fresh coriander leaves. Serve hot with rice, naan, or roti. ",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 30g",
                "Fat":"18g",
                "Fiber":"3g",
                "Carbohydrates":"10g",
            },
        },

        {
            "id": 13,
            "img": "Dishes Images/Lucknowi mutton.jpg",
            "name": "Lucknowi Mutton",
            "typeofDish": "Non-Veg",
            "preparationTime": "20 minutes ",
            "cockingTime": " 1 hour 30 minutes ",
            "totalTime": "1 hour 50 minutes ",
            "Serving": "4 servings",
            "inngredients": " 500g mutton (goat or lamb, cut into pieces), 1/2 cup plain yogurt, 2 tablespoons ginger-garlic paste, 1 tablespoon lemon juice, 1 teaspoon red chili powder,1/2 teaspoon turmeric powder,1 teaspoon ground coriander, 1 teaspoon garam masala, 1/2 teaspoon cumin powder, 2 tablespoons ghee or oil, 2 large onions, finely sliced, 2 tomatoes, chopped or pureed, 1 tablespoon ginger-garlic paste, 2-3 green chilies, slit (optional), 1/2 teaspoon turmeric powder, 1 teaspoon red chili powder, 1 teaspoon ground coriander, 1 teaspoon garam masala, 1/2 teaspoon saffron threads (optional),Fresh coriander leaves for garnish, Salt to taste.",
            "instructions": [
                " In a large bowl, combine yogurt, ginger-garlic paste, lemon juice, red chili powder, turmeric powder, ground coriander, garam masala, cumin powder, and salt.  ",
                "Add the mutton pieces and mix well. Cover and refrigerate for at least 1 hour, or overnight for best results. ",
                "- Heat ghee or oil in a large heavy-bottomed pan over medium heat. Add the sliced onions and sauté until golden brown. Add ginger-garlic paste and cook until the raw smell disappears. Add chopped or pureed tomatoes and cook until the oil starts separating from the mixture.",
                " Add turmeric powder, red chili powder, ground coriander, and garam masala to the onion-tomato mixture. Add the marinated mutton and cook on medium heat for 10-15 minutes, stirring occasionally. ",
                "Add 1-2 cups of water to cover the mutton. If using saffron, dissolve it in a little warm water and add it to the curry. Cover and cook on low heat for 1-1.5 hours, or until the mutton is tender and the gravy has thickened. Stir occasionally and add more water if needed.",
                "Garnish with fresh coriander leaves. Serve hot with naan, roti, or rice.",
            ],
            "nurtrition": {
                "Calories":"400 kcal",
                "Protein":" 30g",
                "Fat":"25g",
                "Fiber":"3g",
                "Carbohydrates":"12g",
            },
        },

        {
            "id": 14,
            "img": "Dishes Images/chicken korma.jpg",
            "name": "Chicken Korma",
            "typeofDish": "Non-Veg",
            "preparationTime": " 20 minutes",
            "cockingTime": "45 minutes ",
            "totalTime": "1 hour 5 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g chicken (cut into pieces), 1/2 cup plain yogurt, 1 tablespoon ginger-garlic paste, 1 tablespoon lemon juice, 1 teaspoon ground coriander,1/2 teaspoon turmeric powder, 1 teaspoon red chili powder, 2 tablespoons ghee or oil,2 large onions, finely sliced1/4 cup cashew nuts (soaked in warm water for 30 minutes), 1/4 cup coconut, grated or desiccated (optional),1 tablespoon ginger-garlic paste,1/2 teaspoon turmeric powder,1 teaspoon red chili powder, 1 teaspoon ground coriander, 1 teaspoon garam masala,1/2 teaspoon ground cardamom, 1/2 teaspoon ground cinnamon,1/2 cup cream or coconut milk, Fresh coriander leaves for garnish, Salt to taste.",
            "instructions": [
                "In a bowl, mix yogurt, ginger-garlic paste, lemon juice, ground coriander, turmeric powder, red chili powder, and salt. Add the chicken pieces and coat them well. Cover and refrigerate for at least 1 hour, or overnight for best results. ",
                "Heat ghee or oil in a large pan over medium heat. Add the sliced onions and cook until golden brown. Remove half for garnishing later. Add ginger-garlic paste to the remaining onions and cook until the raw smell disappears. ",
                "Blend the soaked cashew nuts and grated coconut into a smooth paste using a little water.",
                "Add the turmeric powder, red chili powder, ground coriander, garam masala, ground cardamom, and ground cinnamon to the onion mixture. Add the marinated chicken and cook until the chicken is browned.",
                "Stir in the nut and coconut paste, mix well, and cook for a few minutes. Add cream or coconut milk and cook on low heat for 20-25 minutes, or until the chicken is cooked through and the sauce is thickened. ",
                "Garnish with the reserved fried onions and fresh coriander leaves. Serve hot with naan, roti, or rice. ",
            ],
            "nurtrition": {
                "Calories":"400 kcal",
                "Protein":" 30g",
                "Fat":"25g",
                "Fiber":"3g",
                "Carbohydrates":"15g",
            },
        },

        {
            "id": 15,
            "img": "Dishes Images/fish tikka.jpg",
            "name": " Fish Tikka",
            "typeofDish": "Non-Veg",
            "preparationTime": "15 minutes",
            "cockingTime": " 1 hour (Marination Time) + 15 minutes ",
            "totalTime": " 1 hour 30 minutes ",
            "Serving": "4 servings",
            "inngredients": "500g firm white fish (such as cod, haddock, or tilapia), cut into chunks, 1/2 cup plain yogurt,2 tablespoons lemon juice, 1 tablespoon ginger-garlic paste,1 teaspoon red chili powder, 1/2 teaspoon turmeric powder,1 teaspoon ground coriander,1 teaspoon garam masala, 1/2 teaspoon cumin powder, 1/2 teaspoon paprika (for color), Fresh coriander leaves, Lemon wedges, Sliced onions, Salt to taste. ",
            "instructions": [
                " In a bowl, mix yogurt, lemon juice, ginger-garlic paste, red chili powder, turmeric powder, ground coriander, garam masala, cumin powder, paprika, and salt.  ",
                "Add the fish pieces and coat them well with the marinade. Cover and refrigerate for at least 1 hour. ",
                " Preheat your grill or oven to 200°C (400°F). If using a grill, ensure it is preheated and well-oiled. ",
                " If using a grill, thread the marinated fish pieces onto skewers. Grill the fish for 10-15 minutes, turning occasionally, until it is cooked through and has a nice charred surface. ",
                "If using an oven, place the fish pieces on a baking tray lined with foil or parchment paper. Bake for 12-15 minutes, or until the fish is cooked through and slightly charred. ",
                "Garnish with fresh coriander leaves, lemon wedges, and sliced onions. Serve hot with naan, roti, or as an appetizer with mint chutney. ",
            ],
            "nurtrition": {
                "Calories":"250 kcal",
                "Protein":" 30g",
                "Fat":"10g",
                "Fiber":"2g",
                "Carbohydrates":"10g",
            },
        },

        {
            "id": 16,
            "img": "Dishes Images/prawn biryani.jpg",
            "name": "Prawn Biryani",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"400 kcal",
                "Protein":" 25g",
                "Fat":"15g",
                "Fiber":"3g",
                "Carbohydrates":"45g",
            },
        },

        {
            "id": 17,
            "img": "Dishes Images/lamb vindaloo.jpg",
            "name": "Lamb Vindaloo",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"450 kcal",
                "Protein":" 30g",
                "Fat":"15g",
                "Fiber":"4g",
                "Carbohydrates":"12g",
            },
        },


        {
            "id": 18,
            "img": "Dishes Images/chicken saag.jpg",
            "name": "Chicken saag",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 30g",
                "Fat":"15g",
                "Fiber":"4g",
                "Carbohydrates":"12g",
            },
        },


        {
            "id": 19,
            "img": "Dishes Images/mutton korma.jpg",
            "name": "Mutton Korma",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 30g",
                "Fat":"30g",
                "Fiber":"4g",
                "Carbohydrates":"12g",
            },
        },


        {
            "id": 20,
            "img": "Dishes Images/chicken haleem.jpg",
            "name": "Chicken Haleem",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"500 kcal",
                "Protein":" 35g",
                "Fat":"20g",
                "Fiber":"10g",
                "Carbohydrates":"45g",
            },
        },


        {
            "id": 21,
            "img": "Dishes Images/palak paneer.jpg",
            "name": "Palak paneer",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"240 kcal",
                "Protein":" 12g",
                "Fat":"16g",
                "Fiber":"4g",
                "Carbohydrates":"10g",
            },
        },


        {
            "id": 22,
            "img": "Dishes Images/chana masala.jpg",
            "name": "Chana Masala",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"270 kcal",
                "Protein":" 12g",
                "Fat":"7g",
                "Fiber":"10g",
                "Carbohydrates":"38g",
            },
        },


        {
            "id": 23,
            "img": "Dishes Images/saag aloo.jpg",
            "name": "Saag Aloo",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"200 kcal",
                "Protein":" 6g",
                "Fat":"10g",
                "Fiber":"6g",
                "Carbohydrates":"22g",
            },
        },


        {
            "id": 24,
            "img": "Dishes Images/vegetable korma.jpg",
            "name": "Vegetable Korma",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 6g",
                "Fat":"18g",
                "Fiber":"6g",
                "Carbohydrates":"30g",
            },
        },


        {
            "id": 25,
            "img": "Dishes Images/dal makhani.jpg",
            "name": "Dal Makhani",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 14g",
                "Fat":"16g",
                "Fiber":"12g",
                "Carbohydrates":"36g",
            },
        },


        {
            "id": 26,
            "img": "Dishes Images/mattar paneer.jpeg",
            "name": "Mattar Paneer",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 12g",
                "Fat":"20g",
                "Fiber":"5g",
                "Carbohydrates":"18g",
            },
        },


        {
            "id": 27,
            "img": "Dishes Images/baingan bharta.jpg",
            "name": "Baingan Bharta",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"140 kcal",
                "Protein":" 3g",
                "Fat":"8g",
                "Fiber":"7g",
                "Carbohydrates":"16g",
            },
        },


        {
            "id": 28,
            "img": "Dishes Images/vegetable biryani.jpg",
            "name": "Vegetable Biryani",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"400 kcal",
                "Protein":" 8g",
                "Fat":"12g",
                "Fiber":"6g",
                "Carbohydrates":"60g",
            },
        },


        {
            "id": 29,
            "img": "Dishes Images/rajma masala.jpg",
            "name": "Rajma Masala",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"290 kcal",
                "Protein":" 13g",
                "Fat":"20g",
                "Fiber":"4g",
                "Carbohydrates":"16g",
            },
        },


        {
            "id": 30,
            "img": "Dishes Images/Gobhi manchurian.jpg",
            "name": "Gobi Manchurian",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"280 kcal",
                "Protein":" 5g",
                "Fat":"16g",
                "Fiber":"6g",
                "Carbohydrates":"32g",
            },
        },


        {
            "id": 31,
            "img": "Dishes Images/tofu tikka masala.jpg",
            "name": "Tofu Tikka Masala",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"320 kcal",
                "Protein":" 15g",
                "Fat":"20g",
                "Fiber":"4g",
                "Carbohydrates":"16g",
            },
        },


        {
            "id": 32,
            "img": "Dishes Images/palak tofu.jpg",
            "name": "Palak Tofu",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"240 kcal",
                "Protein":" 14g",
                "Fat":"7g",
                "Fiber":"6g",
                "Carbohydrates":"20g",
            },
        },


        {
            "id": 33,
            "img": "Dishes Images/mixed vegetables sabzi.jpg",
            "name": "Mixed Vegetable Sabzi",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"150 kcal",
                "Protein":" 4g",
                "Fat":"7g",
                "Fiber":"6g",
                "Carbohydrates":"20g",
            },
        },


        {
            "id": 34,
            "img": "Dishes Images/paneer tikka.jpg",
            "name": "Paneer Tikka",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 14g",
                "Fat":"20g",
                "Fiber":"7g",
                "Carbohydrates":"16g",
            },
        },


        {
            "id": 35,
            "img": "Dishes Images/baingan ka bharta.jpg",
            "name": "Baingan Ka Bharta",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"140 kcal",
                "Protein":" 3g",
                "Fat":"8g",
                "Fiber":"7g",
                "Carbohydrates":"16g",
            },
        },


        {
            "id": 36,
            "img": "Dishes Images/aloo gobi.jpg",
            "name": "Aloo Gobi",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"200 kcal",
                "Protein":" 5g",
                "Fat":"10g",
                "Fiber":"6g",
                "Carbohydrates":"24g",
            },
        },


        {
            "id": 37,
            "img": "Dishes Images/matar mushroom.jpg",
            "name": "Matar Mushroom",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"180 kcal",
                "Protein":" 6g",
                "Fat":"10g",
                "Fiber":"4g",
                "Carbohydrates":"18g",
            },
        },


        {
            "id": 38,
            "img": "Dishes Images/vegetable jalfrezi.jpg",
            "name": "Vegetable Jalfrezi",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"190 kcal",
                "Protein":" 6g",
                "Fat":"9g",
                "Fiber":"6g",
                "Carbohydrates":"22g",
            },
        },


        {
            "id": 39,
            "img": "Dishes Images/sag paneer.jpg",
            "name": "Saag Paneer",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"240 kcal",
                "Protein":" 12g",
                "Fat":"30g",
                "Fiber":"6g",
                "Carbohydrates":"10g",
            },
        },


        {
            "id": 40,
            "img": "Dishes Images/kaju curry.jpg",
            "name": "Kaju Curry",
            "typeofDish": "Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"400 kcal",
                "Protein":" 8g",
                "Fat":"30g",
                "Fiber":"4g",
                "Carbohydrates":"24g",
            },
        },


        {
            "id": 41,
            "img": "Dishes Images/Nihar.jpg",
            "name": "Nihari",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"500 kcal",
                "Protein":" 35g",
                "Fat":"25g",
                "Fiber":"6g",
                "Carbohydrates":"30g",
            },
        },


        {
            "id": 42,
            "img": "Dishes Images/mutton paya.jpg",
            "name": "Mutton Paya",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 25g",
                "Fat":"22g",
                "Fiber":"2g",
                "Carbohydrates":"8g",
            },
        },


        {
            "id": 43,
            "img": "Dishes Images/chicken chettinad.jpg",
            "name": "Chicken Chettinad",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 30g",
                "Fat":"20g",
                "Fiber":"3g",
                "Carbohydrates":"10g",
            },
        },


        {
            "id": 44,
            "img": "Dishes Images/chicken handi.jpg",
            "name": "Chicken Handi",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"400 kcal",
                "Protein":" 35g",
                "Fat":"22g",
                "Fiber":"4g",
                "Carbohydrates":"15g",
            },
        },


        {
            "id": 45,
            "img": "Dishes Images/mutton handi.jpg",
            "name": "Mutton Handi",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"450 kcal",
                "Protein":" 30g",
                "Fat":"30g",
                "Fiber":"4g",
                "Carbohydrates":"12g",
            },
        },


        {
            "id": 46,
            "img": "Dishes Images/mutton dum biryani.jpg",
            "name": "Mutton Dum Biryani",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"500 kcal",
                "Protein":" 30g",
                "Fat":"20g",
                "Fiber":"3g",
                "Carbohydrates":"50g",
            },
        },


        {
            "id": 47,
            "img": "Dishes Images/chicken dum biryani.jpg",
            "name": "Chicken Dum Biryani",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"450 kcal",
                "Protein":" 35g",
                "Fat":"15g",
                "Fiber":"3g",
                "Carbohydrates":"50g",
            },
        },


        {
            "id": 48,
            "img": "Dishes Images/mutton liver fry.jpg",
            "name": "Mutton Liver Fry",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"350 kcal",
                "Protein":" 30g",
                "Fat":"20g",
                "Fiber":"8g",
                "Carbohydrates":"8g",
            },
        },


        {
            "id": 49,
            "img": "Dishes Images/chicken liver fry.jpg",
            "name": "Chicken Liver Fry",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"300 kcal",
                "Protein":" 28g",
                "Fat":"20g",
                "Fiber":"2g",
                "Carbohydrates":"8g",
            },
        },


        {
            "id": 50,
            "img": "Dishes Images/fish pepper fry.jpg",
            "name": "Fish Peppar Fry",
            "typeofDish": "Non-Veg",
            "preparationTime": "",
            "cockingTime": "",
            "totalTime": "",
            "Serving": "4 servings",
            "inngredients": "",
            "instructions": [
                "",
                "",
                "",
                "",
                "",
                "",
            ],
            "nurtrition": {
                "Calories":"250 kcal",
                "Protein":" 30g",
                "Fat":"18g",
                "Fiber":"2g",
                "Carbohydrates":"6g",
            },
        },


        

]